### ISSUE TITLE
More visual

### ISSUE THREAD

**Issue by Thendo-T** [Thendo-T/Calculator#1]

**Comment by aseemsahoo** [comment]
You could assign this to me.

**Comment by Thendo-T** [comment]
Sure

**Comment by Thendo-T** [comment]
@aseemsahoo Should I add you as a contributor, since you still have some back-end to add?

**Comment by aseemsahoo** [comment]
Yeah, do add me. I'll try to manage the back-end functions.
Thanks!

**Comment by Thendo-T** [comment]
cool
